import 'package:flutter/material.dart';

const kMainColor = Color(0xFFFFFFFF);
const kSecondaryColor = Color(0xFF568DDF);
const kPurpleColor = Color(0xFFBC6A99);
const kGreyLight = Color(0xFF6AADBC);
const kBlueLightColor = Color(0xFF6A86BC);
const kYellowColor = Color(0xFFEAA95A);
const kBrownrColor = Color(0xFFD47560);
const kBlackColor = Color(0xFF000000);
const kGreyDarkColor = Color(0xFF717171);
const kWhiteLightColor = Color(0xFFE9E9E9);
const kWhiteColor = Color(0xFFF4F4F4);
const kPinkLightColor = Color(0xFFF7E9FF);
const kOrangeLightColor = Color(0xFFFFEFCF);
const kSkyLightColor = Color(0xFFE9F3FF);
const ktColor = Color(0xFFf5f8fd);
const kRedColor = Color(0xFFD25353);
const kDarkBlueColor = Color(0xFF9A53D2);
const kGreenColor = Color(0xFF53D258);
const kLowVisblilePinkColor = Color(0xFFFBECFF);
const kOrangeDarkColor = Color(0xFFFF8A1E);
